class LanguageManager:
    def __init__(self):
        self.current_language = "English" # Default language set to english
        self.translations = {
            "English": {
                "app_title": "Password Manager",
                "reg_title": "Password Manager",
                "reg_signin": "Sign In",
                "reg_login": "Log In",
                "signin_title": "SIGN IN",
                "signin_text_label": "Please enter a username for the account creation",
                "signin_entry_placeholder": "Username",
                "signin_generate": "Generate",
                "signin_back": "Back",
                "signin_popup_lenght": "Please make sure to enter a proper username (min. 3 max. 48 letters)",
                "signin_popup_spaces": "Please make sure not to enter spaces or replace them with _",
                "qrcode_title": "QR Code",
                "qrcode_back": "Done",
                "login_title": "LOG IN",
                "login_username_label": "Please enter your username",
                "login_username_placeholder_entry": "Username",
                "login_token_label": "Please enter a valid validation token",
                "login_generate": "Log In",
                "login_back": "Back",
                "login_user_token_popup": "Please make sure you enter an existing username and a valid token",
                "login_token_popup": "Please make sure you enter a valid token",
                "nav_title": "PASSWORD MANAGER",
                "nav_pwd": "PASSWORDS",
                "nav_add": "ADD",
                "nav_modify": "MODIFY",
                "nav_remove": "REMOVE",
                "nav_gen_pwd": "GENERATE PASSWORD",
                "nav_sys_lan_eng": "English",
                "nav_sys_lan_spa": "Spanish",
                "nav_sys_lan_ger": "German",
                "nav_sys_color_light": "Light",
                "nav_sys_color_dark": "Dark",
                "nav_sys_color_system": "System",
                "get_key": "Show Key",
                "pwd_id": "ID",
                "pwd_app": "Application",
                "pwd_username": "Username",
                "add_app": "Application",
                "add_username": "Username",
                "add_username_label": "example@outlook.com",
                "add_pwd": "Password",
                "add_pwd_label": "my_password",
                "add_clear_button": "Clear",
                "add_add_button": "Add",
                "add_popup": "Please enter values in all the inputs",
                "modify_username": "Username",
                "modify_username_label": "example@outlook.com",
                "modify_pwd": "Password",
                "modify_pwd_label": "my_password",
                "modify_clear_button": "Clear",
                "modify_modify_button": "Modify",
                "modify_all_values_popup": "Please enter values in all the inputs",
                "modify_validID_popup": "Please make sure to enter a valid ID",
                "modify_selectedID_popup": "No ID was selected. Please make sure to enter a valid ID",
                "remove_title": "Select ID to be removed",
                "remove_button": "Delete",
                "remove_validID_popup": "Please make sure to enter a valid ID",
                "remove_selectedID_popup": "No ID was selected. Please make sure to enter a valid ID", 
                "gen_title": "Please select the needed options to generate the password",
                "gen_sub_title": "Enter the amount of characters needed",
                "gen_choise1": "Uppercase",
                "gen_choise2": "Digits",
                "gen_choise3": "Special Characters",
                "gen_gen_button": "Generate",
                "gen_pwd_generated_popup": "Password generated!",
                "gen_valid_popup": "Please make sure to entry a valid digit (max 100)"
            },
            "Spanish": {
                "app_title": "Administrador de Contraseñas",
                "reg_title": "Administrador de Contraseñas",
                "reg_signin": "Crear Cuenta",
                "reg_login": "Iniciar sesion",
                "signin_title": "CREAR CUENTA",
                "signin_text_label": "Por favor ingrese un nombre de usuario para la creación de la cuenta",
                "signin_entry_placeholder": "Nombre de usuario",
                "signin_generate": "Generar",
                "signin_back": "Atrás",
                "signin_popup_lenght": "Por favor, asegúrese de introducir un nombre de usuario adecuado (mín. 3 máx. 48 letras)",
                "signin_popup_spaces": "Asegúrese de no introducir espacios, o sustitúyalos por _",
                "qrcode_title": "Código QR",
                "qrcode_back": "Listo",
                "login_title": "INICIAR SESION",
                "login_username_label": "Por favor, introduzca su nombre de usuario",
                "login_username_placeholder_entry": "Nombre de usuario",
                "login_token_label": "Por favor, introduzca el token de validación",
                "login_generate": "Iniciar sesion",
                "login_back": "Atrás",
                "login_user_token_popup": "Asegúrese de introducir un nombre de usuario existente y un token válido.",
                "login_token_popup": "Asegúrese de introducir un token válido",
                "nav_title": "ADMIN CONTRASEÑAS",
                "nav_pwd": "CONTRASEÑAS",
                "nav_add": "AGREGAR",
                "nav_modify": "MODIFICAR",
                "nav_remove": "ELIMINAR",
                "nav_gen_pwd": "GENERAR CONTRASEÑA",
                "nav_sys_lan_eng": "English",
                "nav_sys_lan_spa": "Spanish",
                "nav_sys_lan_ger": "German",
                "nav_sys_color_light": "Claro",
                "nav_sys_color_dark": "Oscuro",
                "nav_sys_color_system": "Systema",
                "get_key": "Mostrar clave",
                "pwd_id": "ID",
                "pwd_app": "Programa",
                "pwd_username": "Nombre de usuario",
                "add_app": "Programa",
                "add_username": "Nombre de usuario",
                "add_username_label": "ejemplo@outlook.com",
                "add_pwd": "Contraseña",
                "add_pwd_label": "mi_contraseña",
                "add_clear_button": "Borrar",
                "add_add_button": "Agregar",
                "add_popup": "Introduzca valores en todas las entradas",
                "modify_username": "Nombre de usuario",
                "modify_username_label": "ejemplo@outlook.com",
                "modify_pwd": "Contraseña",
                "modify_pwd_label": "mi_contraseña",
                "modify_clear_button": "Borrar",
                "modify_modify_button": "Modificar",
                "modify_all_values_popup": "Asegúrese de introducir valores en todas las entradas",
                "modify_validID_popup": "Asegúrese de introducir una ID válida",
                "modify_selectedID_popup": "No se ha seleccionado ningún ID. Por favor, asegúrese de introducir un ID válido",
                "remove_title": "Seleccione el ID que desea eliminar",
                "remove_button": "Eliminar",
                "remove_validID_popup": "Asegúrese de introducir una ID válida",
                "remove_selectedID_popup": "No se ha seleccionado ningún ID. Por favor, asegúrese de introducir un ID válido",
                "gen_title": "Seleccione las opciones necesarias para generar la contraseña",
                "gen_sub_title": "Introduzca la cantidad de caracteres necesarios",
                "gen_choise1": "Mayúsculas",
                "gen_choise2": "Dígitos",
                "gen_choise3": "Signos",
                "gen_gen_button": "Generar",
                "gen_pwd_generated_popup": "Contraseña generada!",
                "gen_valid_popup": "Asegúrese de introducir un dígito válido (máx. 100)"
            },
            "German": {
                "app_title": "Passwort Manager",
                "reg_title": "Passwort Manager",
                "reg_signin": "Einloggen",
                "reg_login": "Anmelden",
                "signin_title": "EINLOGGEN",
                "signin_text_label": "Bitte geben Sie einen Benutzernamen für die Kontoerstellung ein",
                "signin_entry_placeholder": "Nutzername",
                "signin_generate": "Generieren",
                "signin_back": "Zurück",
                "signin_popup_lenght": "Bitte stellen Sie sicher, dass Sie einen korrekten Benutzernamen eingeben (min. 3 max. 48 Buchstaben)",
                "signin_popup_spaces": "Bitte achten Sie darauf, keine Leerzeichen einzugeben oder ersetzten Sie diese durch _",
                "qrcode_title": "QR-Code",
                "qrcode_back": "Fertig",
                "login_title": "ANMELDEN",
                "login_username_label": "Bitte geben Sie Ihren Benutzernamen ein",
                "login_username_placeholder_entry": "Nutzername",
                "login_token_label": "Bitte geben Sie ein gültiges Validierungstoken ein",
                "login_generate": "Anmelden",
                "login_back": "Zurück",
                "login_user_token_popup": "Bitte stellen Sie sicher, dass Sie einen bestehenden Benutzernamen und ein gültiges Token eingeben",
                "login_token_popup": "Bitte stellen Sie sicher, dass Sie einen gültigen Token eingeben",
                "nav_title": "Passwort Manager",
                "nav_pwd": "PASSWORT",
                "nav_add": "HINZUFÜGEN",
                "nav_modify": "ÄNDERN",
                "nav_remove": "ENTFERNEN",
                "nav_gen_pwd": "PASSWORT GENERIEREN",
                "nav_sys_lan_eng": "English",
                "nav_sys_lan_spa": "Spanish",
                "nav_sys_lan_ger": "German",
                "nav_sys_color_light": "Hell",
                "nav_sys_color_dark": "Dunkel",
                "nav_sys_color_system": "System",
                "get_key": "Schlüssel anzeigen",
                "pwd_id": "ID",
                "pwd_app": "Programm",
                "pwd_username": "Nutzername",
                "add_app": "Programm",
                "add_username": "Nutzername",
                "add_username_label": "beispiel@outlook.com",
                "add_pwd": "Passwort",
                "add_pwd_label": "mein_Passwort",
                "add_clear_button": "Leeren",
                "add_add_button": "Hinzufügen",
                "add_popup": "Bitte geben Sie bei allen Eingaben Werte ein",
                "modify_username": "Nutzername",
                "modify_username_label": "beispiel@outlook.com",
                "modify_pwd": "Passwort",
                "modify_pwd_label": "mein_Passwort",
                "modify_clear_button": "Leeren",
                "modify_modify_button": "Ändern",
                "modify_all_values_popup": "Bitte geben Sie bei allen Eingaben Werte ein",
                "modify_validID_popup": "Bitte stellen Sie sicher, dass Sie eine gültige ID eingeben",
                "modify_selectedID_popup": "Es wurde keine ID ausgewählt. Bitte stellen Sie sicher, dass Sie eine gültige ID eingeben",
                "remove_title": "Wählen Sie die zu entfernende ID aus",
                "remove_button": "Löschen",
                "remove_validID_popup": "Bitte stellen Sie sicher, dass Sie eine gültige ID eingeben",
                "remove_selectedID_popup": "Es wurde keine ID ausgewählt. Bitte stellen Sie sicher, dass Sie eine gültige ID eingeben",
                "gen_title": "Bitte wählen Sie die erforderlichen Optionen aus, um das Passwort zu generieren",
                "gen_sub_title": "Geben Sie die Anzahl der benötigten Zeichen ein",
                "gen_choise1": "Grossbuchstaben",
                "gen_choise2": "Zahlen",
                "gen_choise3": "Sonderzeichen",
                "gen_gen_button": "Generieren",
                "gen_pwd_generated_popup": "Passwort generiert!",
                "gen_valid_popup": "Bitte stellen Sie sicher, dass Sie eine gültige Ziffer eingeben (max. 100)"
            }
        }
    # Sets language to defined language
    def set_language(self, language):
        self.current_language = language

    # Get language currently in use
    def get_language(self):
        return self.current_language

    # Gets text based on current language
    def get_text(self, key):
        if self.current_language in self.translations:
            language_dict = self.translations[self.current_language]
            if key in language_dict:
                return language_dict[key]
        return "Translation not found"